import { cookies } from 'next/headers';
import { ClientCookiesProvider } from '@/components/client';
import { Providers } from '@/components/client';
import { ReactNode, Locale } from '@/types';
import { Lora } from 'next/font/google';

const lora = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lora',
});

export const metadata = {
  title: 'Bemp Research',
  description: 'Generated by Sieutoc Platform',
};

// Cause trouble with server actions
// Read more: https://github.com/vercel/next.js/issues/54992
// export async function generateStaticParams() {
//   return i18n.locales.map((locale) => ({ locale }));
// }

export default async function RootLayout({
  children, // params,
}: {
  children: ReactNode;
  params: { locale: Locale };
}) {
  return (
    <html lang="en" className={lora.variable}>
      <body>
        <ClientCookiesProvider value={cookies().getAll()}>
          <Providers>{children}</Providers>
        </ClientCookiesProvider>
      </body>
    </html>
  );
}
